name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_VAR_region: eu-west-2
  AWS_ACCOUNT_ID: "175798131198" # Directly provided

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    environment:
      name: Asli
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3 # Explicitly specified version
        with:
          name: tfplan

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::175798131198:role/Github_Role_Demo
          aws-region: "eu-west-2"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -input=false tfplan
