name: Terraform CI CD Pipeline for Deploying AWS Resources

on:
  push:
    branches:
      - "*"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_VAR_region: eu-west-2

jobs:
  build-infra:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::175798131198:role/Github_Role_Demo
          aws-region: "eu-west-2"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"

      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/download/v1.28.3/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          mv tfsec-linux-amd64 /usr/local/bin/tfsec

      - name: Run tfsec
        run: tfsec .
