name: Terraform CI CD Pipeline for Deploying AWS Resources

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_VAR_region: eu-west-2

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::175798131198:role/Github_Role_Demo
          aws-region: "eu-west-2"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false -var-file="terraform.tfvars"
          echo "Terraform plan completed."

      - name: Save Plan Output
        run: |
          terraform plan -out=tfplan
          echo "Plan saved as tfplan"
        id: save_plan

      - name: Upload Plan Output
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Run tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/download/v1.28.3/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          mv tfsec-linux-amd64 /usr/local/bin/tfsec
          tfsec .

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: Asli
